<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 引用惯性和质量的宏文件 -->
    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro"/>
    <!-- 机器人身体部分 -->
    <xacro:macro name="base_xacro" params="length radius">
        <!-- 设置地面 xy一致，z刚好在中心点,是投影-->
        <link name="base_footprint"/>
        <link name="base_link">
            <!-- 部件外观描述 -->
            <visual>
                <!-- 沿自己几何中心的偏移与旋转量 -->
                <origin xyz="0 0 0" rpy="0 0 0" />
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体，半径0.1m，高度 0.12m -->
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <!-- 材质子标签-白色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5" />
                </material>
            </visual>
            <!-- 碰撞属性 -->
            <collision>
                 <!-- 沿自己几何中心的偏移与旋转量 -->
                <origin xyz="0 0 0" rpy="0 0 0" />
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体，半径0.1m，高度 0.12m -->
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <!-- 材质子标签-白色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5" />
                </material>
            </collision>
            <!-- 添加惯性和质量 -->
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
        </link>
        <joint name="joint_name" type="fixed">
            <!-- 基础部件高度的一半+轮子的高度-一点距离-->
             <!-- 子部件相对父部件的平移和旋转 -->
            <origin xyz="0.0 0.0 ${length/2.0 +0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>
    </xacro:macro>
  

</robot>